version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    container_name: postgres_db_rel
    ports:
      - '5432'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'contacts_app'
  app:
    image: contacts_crud
    container_name: contacts_crud
    build: .
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'contacts_app'
    ports:
      - 8080:8080
    depends_on:
      - "postgres"
    restart:
      always
