postgres:
 image: postgres:9.6-alpine
 container_name: postgres_db_test
 ports:
   - '5566:5432'
 environment:
   POSTGRES_USER: 'postgres'
   POSTGRES_PASSWORD: 'postgres'
   POSTGRES_DB: 'contacts_app'
 volumes:
   - ./schema:/docker-entrypoint-initdb.d