-define(CONTACT_1_EMAIL, <<"user@example.com">>).
-define(CONTACT_1_SURNAME, <<"contact_surname_1">>).
-define(CONTACT_1_NAME, <<"contact_name_1">>).
-define(CONTACT_1_PHONE_NUMBER, <<"12332123">>).

-define(CONTACT_1, [?CONTACT_1_EMAIL, ?CONTACT_1_NAME, ?CONTACT_1_SURNAME, ?CONTACT_1_PHONE_NUMBER]).
-define(CONTACT_1_TUPLE, {?CONTACT_1_EMAIL, ?CONTACT_1_NAME, ?CONTACT_1_SURNAME, ?CONTACT_1_PHONE_NUMBER}).

-define(CONTACT_2_EMAIL, <<"user2@example.com">>).
-define(CONTACT_2_SURNAME, <<"a_contact_surname_2">>).
-define(CONTACT_2_NAME, <<"contact_name_2">>).
-define(CONTACT_2_PHONE_NUMBER, <<"23453421">>).
-define(CONTACT_2, [?CONTACT_2_EMAIL, ?CONTACT_2_NAME, ?CONTACT_2_SURNAME, ?CONTACT_2_PHONE_NUMBER]).
-define(CONTACT_2_TUPLE, {?CONTACT_2_EMAIL, ?CONTACT_2_NAME, ?CONTACT_2_SURNAME, ?CONTACT_2_PHONE_NUMBER}).
-define(CONTACT_2_UPDATE, [?CONTACT_2_EMAIL, ?CONTACT_1_NAME, ?CONTACT_1_SURNAME, ?CONTACT_1_PHONE_NUMBER]).

-define(CONTACT_1_UPDATED_SURNAME, <<"updated surname">>).
-define(CONTACT_1_UPDATED_NAME, <<"updated name">>).
-define(CONTACT_1_UPDATED_PHONE_NUMBER, <<"8912398">>).
-define(CONTACT_1_UPDATE, [?CONTACT_1_EMAIL, ?CONTACT_1_UPDATED_NAME, ?CONTACT_1_UPDATED_SURNAME, ?CONTACT_1_UPDATED_PHONE_NUMBER]).
-define(CONTACT_1_UPDATE_TUPLE, {?CONTACT_1_EMAIL, ?CONTACT_1_UPDATED_NAME, ?CONTACT_1_UPDATED_SURNAME, ?CONTACT_1_UPDATED_PHONE_NUMBER}).